application: colarte-dev
version: 1

runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  expiration: 1d

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

# if you're adding the shell to your own app, change this regex url to the URL
# endpoint where you want the shell to run, e.g. /shell . You'll also probably
# want to add login: admin to restrict to admins only.
- url: .*
  script: main.py

- url: /addcategory
  script: main.py

- url: /proc_add_category
  script: main.py

- url: /listcategory
  script: main.py


- url: /upload_file
  script: main.py

- url: /proc_file_upload
  script: main.py

- url: /listuploadedfiles
  script: main.py

- url: /addurl
  script: main.py

- url: /proc_add_url
  script: main.py

- url: /listurl
  script: main.py

