;; This file was automatically generated by SWIG (http://www.swig.org).
;; Version 1.3.39
;;
;; Do not make changes to this file unless you know what you are doing--modify
;; the SWIG interface file instead.

(defpackage :magic
  (:use :common-lisp :ffi)
  (:export
	:MAGIC_NONE
	:MAGIC_DEBUG
	:MAGIC_SYMLINK
	:MAGIC_COMPRESS
	:MAGIC_DEVICES
	:MAGIC_MIME_TYPE
	:MAGIC_CONTINUE
	:MAGIC_CHECK
	:MAGIC_PRESERVE_ATIME
	:MAGIC_RAW
	:MAGIC_ERROR
	:MAGIC_MIME_ENCODING
	:MAGIC_MIME
	:MAGIC_APPLE
	:MAGIC_NO_CHECK_COMPRESS
	:MAGIC_NO_CHECK_TAR
	:MAGIC_NO_CHECK_SOFT
	:MAGIC_NO_CHECK_APPTYPE
	:MAGIC_NO_CHECK_ELF
	:MAGIC_NO_CHECK_TEXT
	:MAGIC_NO_CHECK_CDF
	:MAGIC_NO_CHECK_TOKENS
	:MAGIC_NO_CHECK_ENCODING
	:MAGIC_NO_CHECK_ASCII
	:MAGIC_NO_CHECK_FORTRAN
	:MAGIC_NO_CHECK_TROFF
	:magic_open
	:magic_close
	:magic_file
	:magic_descriptor
	:magic_buffer
	:magic_error
	:magic_setflags
	:magic_load
	:magic_compile
	:magic_check
	:magic_errno))

(in-package :magic)
(defconstant +library-name+ "/usr/lib/libmagic.so")

(default-foreign-language :stdc)

(defconstant MAGIC_NONE "0x000000")

(defconstant MAGIC_DEBUG "0x000001")

(defconstant MAGIC_SYMLINK "0x000002")

(defconstant MAGIC_COMPRESS "0x000004")

(defconstant MAGIC_DEVICES "0x000008")

(defconstant MAGIC_MIME_TYPE "0x000010")

(defconstant MAGIC_CONTINUE "0x000020")

(defconstant MAGIC_CHECK "0x000040")

(defconstant MAGIC_PRESERVE_ATIME "0x000080")

(defconstant MAGIC_RAW "0x000100")

(defconstant MAGIC_ERROR "0x000200")

(defconstant MAGIC_MIME_ENCODING "0x000400")

(defconstant MAGIC_MIME "0x000010")

;(defconstant MAGIC_MIME 0x000010|0x000400)
(defconstant MAGIC_APPLE "0x000800")

(defconstant MAGIC_NO_CHECK_COMPRESS "0x001000")

(defconstant MAGIC_NO_CHECK_TAR "0x002000")

(defconstant MAGIC_NO_CHECK_SOFT "0x004000")

(defconstant MAGIC_NO_CHECK_APPTYPE "0x008000")

(defconstant MAGIC_NO_CHECK_ELF "0x010000")

(defconstant MAGIC_NO_CHECK_TEXT "0x020000")

(defconstant MAGIC_NO_CHECK_CDF "0x040000")

(defconstant MAGIC_NO_CHECK_TOKENS "0x100000")

(defconstant MAGIC_NO_CHECK_ENCODING "0x200000")

(defconstant MAGIC_NO_CHECK_ASCII "0x020000")

(defconstant MAGIC_NO_CHECK_FORTRAN "0x000000")

(defconstant MAGIC_NO_CHECK_TROFF "0x000000")

(ffi:def-c-type magic_t ffi:c-pointer)

(ffi:def-call-out magic_open
	(:name "magic_open")
	(:arguments (arg0 ffi:int))
	(:return-type magic_t)
	(:library +library-name+))

(ffi:def-call-out magic_close
	(:name "magic_close")
	(:arguments (arg0 magic_t))
	(:library +library-name+))

(ffi:def-call-out magic_file
	(:name "magic_file")
	(:arguments (arg0 magic_t)
		(arg1 ffi:c-string))
	(:return-type ffi:c-string)
	(:library +library-name+))

(ffi:def-call-out magic_descriptor
	(:name "magic_descriptor")
	(:arguments (arg0 magic_t)
		(arg1 ffi:int))
	(:return-type ffi:c-string)
	(:library +library-name+))

(ffi:def-call-out magic_buffer
	(:name "magic_buffer")
	(:arguments (arg0 magic_t)
		(arg1 (ffi:c-pointer NIL))
		(arg2 size_t))
	(:return-type ffi:c-string)
	(:library +library-name+))

(ffi:def-call-out magic_error
	(:name "magic_error")
	(:arguments (arg0 magic_t))
	(:return-type ffi:c-string)
	(:library +library-name+))

(ffi:def-call-out magic_setflags
	(:name "magic_setflags")
	(:arguments (arg0 magic_t)
		(arg1 ffi:int))
	(:return-type ffi:int)
	(:library +library-name+))

(ffi:def-call-out magic_load
	(:name "magic_load")
	(:arguments (arg0 magic_t)
		(arg1 ffi:c-string))
	(:return-type ffi:int)
	(:library +library-name+))

(ffi:def-call-out magic_compile
	(:name "magic_compile")
	(:arguments (arg0 magic_t)
		(arg1 ffi:c-string))
	(:return-type ffi:int)
	(:library +library-name+))

(ffi:def-call-out magic_check
	(:name "magic_check")
	(:arguments (arg0 magic_t)
		(arg1 ffi:c-string))
	(:return-type ffi:int)
	(:library +library-name+))

(ffi:def-call-out magic_errno
	(:name "magic_errno")
	(:arguments (arg0 magic_t))
	(:return-type ffi:int)
	(:library +library-name+))
